// /*import { useEffect, useState } from "react";
// import api from "../../api";

// import {
//   LineChart,
//   Line,
//   XAxis,
//   YAxis,
//   Tooltip,
//   CartesianGrid,
//   BarChart,
//   Bar,
//   ResponsiveContainer
// } from "recharts";

// export default function Analytics() {
//   const [trend, setTrend] = useState([]);
//   const [heatmap, setHeatmap] = useState([]);

//   useEffect(() => {
//     load();
//   }, []);

//   const load = async () => {
//     try {
//       const t = await api.get("/admin/analytics/risk-trend");
//       const h = await api.get("/admin/analytics/heatmap");

//       setTrend(t.data || []);
//       setHeatmap(h.data || []);
//     } catch (e) {
//       console.log(e);
//     }
//   };

//   return (
//     <div>
//       <h2 className="page-title">📊 Analytics Dashboard</h2>

//       {/* ================= RISK TREND ================= */}
//       <div className="card">
//         <div className="section-title">Risk Trend Over Time</div>

//         <ResponsiveContainer width="100%" height={300}>
//           <LineChart data={trend}>
//             <CartesianGrid strokeDasharray="3 3" />
//             <XAxis dataKey="_id" />
//             <YAxis />
//             <Tooltip />
//             <Line
//               type="monotone"
//               dataKey="total"
//               stroke="#2563eb"
//               strokeWidth={3}
//             />
//           </LineChart>
//         </ResponsiveContainer>
//       </div>

//       {/* ================= HEATMAP ================= */}
//       <div className="card">
//         <div className="section-title">Violations by Hour</div>

//         <ResponsiveContainer width="100%" height={300}>
//           <BarChart data={heatmap}>
//             <CartesianGrid strokeDasharray="3 3" />
//             <XAxis dataKey="_id" />
//             <YAxis />
//             <Tooltip />
//             <Bar dataKey="count" fill="#16a34a" />
//           </BarChart>
//         </ResponsiveContainer>
//       </div>
//     </div>
//   );
// }
import { useEffect, useState } from "react";
import api from "../../api";

export default function Analytics() {
  const [stats, setStats] = useState({
    total: 0,
    high: 0,
    medium: 0,
    low: 0
  });

  useEffect(() => {
    load();
  }, []);

  const load = async () => {
    try {
      const res = await api.get("/activity/admin/all");
      const logs = res.data;

      setStats({
        total: logs.length,
        high: logs.filter(l => l.severity === "HIGH").length,
        medium: logs.filter(l => l.severity === "MEDIUM").length,
        low: logs.filter(l => l.severity === "LOW").length
      });
    } catch {
      alert("Failed to load analytics");
    }
  };

  return (
    <div>
      <h2 className="page-title">📊 Security Analytics</h2>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(4, 1fr)",
          gap: 16
        }}
      >
        <Stat title="Total Events" value={stats.total} />
        <Stat title="High Risk" value={stats.high} />
        <Stat title="Medium Risk" value={stats.medium} />
        <Stat title="Low Risk" value={stats.low} />
      </div>

      <div className="card" style={{ marginTop: 20 }}>
        <h3>📈 System Intelligence</h3>
        <p>
          This dashboard provides a real-time overview of user behavior risk
          classification and security events generated by ComplianceAI.
        </p>

        <ul style={{ marginTop: 12 }}>
          <li>High Risk = Possible fraud, phishing, credential abuse</li>
          <li>Medium Risk = Policy or internal data violations</li>
          <li>Low Risk = Normal user behavior</li>
        </ul>
      </div>
    </div>
  );
}

function Stat({ title, value }) {
  return (
    <div className="card" style={{ textAlign: "center" }}>
      <div style={{ fontSize: 28, fontWeight: 700 }}>{value}</div>
      <div style={{ color: "#64748b" }}>{title}</div>
    </div>
  );
}
